In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

# import SVC classifier
from sklearn.svm import SVC

# import metrics to compute accuracy (Evulate)
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV


In [ ]:
xtrain=pd.read_table('/content/drive/My Drive/UCI_HAR_Dataset/train/X_train.txt',delim_whitespace=True,header=None)

In [ ]:
xtest=pd.read_table('/content/drive/My Drive/UCI_HAR_Dataset/test/X_test.txt',delim_whitespace=True,header=None)

In [ ]:
ytrain=pd.read_table('/content/drive/My Drive/UCI_HAR_Dataset/train/y_train.txt',header=None)

In [ ]:
ytest=pd.read_table('/content/drive/My Drive/UCI_HAR_Dataset/test/y_test.txt',header=None)

In [ ]:
xtrain.head()

0         1         2    ...       558       559       560
0  0.288585 -0.020294 -0.132905  ... -0.841247  0.179941 -0.058627
1  0.278419 -0.016411 -0.123520  ... -0.844788  0.180289 -0.054317
2  0.279653 -0.019467 -0.113462  ... -0.848933  0.180637 -0.049118
3  0.279174 -0.026201 -0.123283  ... -0.848649  0.181935 -0.047663
4  0.276629 -0.016570 -0.115362  ... -0.847865  0.185151 -0.043892

[5 rows x 561 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X = scaler.fit_transform(xtrain)

In [ ]:
x_test=scaler.fit_transform(xtest)

In [ ]:
# instantiate classifier with linear kernel and C=1.0
linear_svc=SVC(kernel='linear', C=1.0) 


# fit classifier to training set
linear_svc.fit(X,ytrain)


# make predictions on test set
y_pred_test=linear_svc.predict(x_test)


# compute and print accuracy score
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(ytest, y_pred_test)))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Model accuracy score with linear kernel and C=1.0 : 0.9623


In [18]:
print(confusion_matrix(ytest,y_pred_test))

[[484   7   5   0   0   0]
 [  8 460   3   0   0   0]
 [  3  11 406   0   0   0]
 [  0   2   0 443  46   0]
 [  0   0   0  26 506   0]
 [  0   0   0   0   0 537]]
